# File automatically generated by Transformer v1.3.0:
# https://github.com/zalando-incubator/Transformer

from distutils.version import LooseVersion
from locust import __version__

LOCUST_MAJOR_VERSION = LooseVersion(__version__).version[0]

if LOCUST_MAJOR_VERSION >= 1:
    from locust import HttpUser
    from locust import SequentialTaskSet
    from locust import TaskSet
    from locust import task
    HttpLocust = HttpUser
    TaskSequence = SequentialTaskSet
    def seq_task(_):
        return task
else:
    from locust import HttpLocust
    from locust import TaskSequence
    from locust import TaskSet
    from locust import seq_task
    from locust import task

class monarch_random_182055_har_2011367572(TaskSequence):
    @seq_task(1)
    def GET_https_monarchinitiative_org_1607665813___3145776_1998636521911357476(self):
        self.client.get(url='/', name='/', timeout=30, allow_redirects=False, headers={'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'cache-control': 'max-age=0', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'document', 'sec-fetch-mode': 'navigate', 'sec-fetch-site': 'none', 'sec-fetch-user': '?1', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(2)
    def GET_https_monarchinitiative_org_1607665813__css_app_fe6b0f90_css_1291257584_795479597689067098(self):
        self.client.get(url='/css/app.fe6b0f90.css', name='/css/app.fe6b0f90.css', timeout=30, allow_redirects=False, headers={'accept': 'text/css,*/*;q=0.1', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'style', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(3)
    def GET_https_monarchinitiative_org_1607665813__css_chunk_vendors_b5fbaf8f_css_3051948888_1460458711782190403(self):
        self.client.get(url='/css/chunk-vendors.b5fbaf8f.css', name='/css/chunk-vendors.b5fbaf8f.css', timeout=30, allow_redirects=False, headers={'accept': 'text/css,*/*;q=0.1', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'style', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(4)
    def GET_https_monarchinitiative_org_1607665813__js_app_20c182fa_js_978191837_525862958161018756(self):
        self.client.get(url='/js/app.20c182fa.js', name='/js/app.20c182fa.js', timeout=30, allow_redirects=False, headers={'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'script', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(5)
    def GET_https_monarchinitiative_org_1607665813__js_chunk_vendors_aee980db_js_2636712526_6822834204114050406(self):
        self.client.get(url='/js/chunk-vendors.aee980db.js', name='/js/chunk-vendors.aee980db.js', timeout=30, allow_redirects=False, headers={'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'script', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(6)
    def GET_https_fonts_googleapis_com_1413416944__css_54657401_7447096099997380012(self):
        self.client.get(url='https://fonts.googleapis.com/css?family=Poppins&display=swap', name='https://fonts.googleapis.com/css?family=Poppins&display=swap', timeout=30, allow_redirects=False, headers={'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(7)
    def GET_https_monarchinitiative_org_1607665813__css_analyze_phenotypes_97154517_css_4062055524_4291845842913689571(self):
        self.client.get(url='/css/analyze-phenotypes.97154517.css', name='/css/analyze-phenotypes.97154517.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(8)
    def GET_https_monarchinitiative_org_1607665813__css_data_sources_785e4cba_css_2747009659_7528689424198996585(self):
        self.client.get(url='/css/data-sources.785e4cba.css', name='/css/data-sources.785e4cba.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(9)
    def GET_https_monarchinitiative_org_1607665813__css_mon_analytics_7772cbcb_css_2960788205_2669806325586412497(self):
        self.client.get(url='/css/mon-analytics.7772cbcb.css', name='/css/mon-analytics.7772cbcb.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(10)
    def GET_https_monarchinitiative_org_1607665813__css_routeerror_53caa0d4_css_2494761467_2416210844668902666(self):
        self.client.get(url='/css/routeerror.53caa0d4.css', name='/css/routeerror.53caa0d4.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(11)
    def GET_https_monarchinitiative_org_1607665813__css_search_54cc5d84_css_1701578743_8125423801947113379(self):
        self.client.get(url='/css/search.54cc5d84.css', name='/css/search.54cc5d84.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(12)
    def GET_https_monarchinitiative_org_1607665813__css_text_annotate_48d8c4b0_css_2982939338_4172001603193913218(self):
        self.client.get(url='/css/text-annotate.48d8c4b0.css', name='/css/text-annotate.48d8c4b0.css', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(13)
    def GET_https_monarchinitiative_org_1607665813__js_analyze_phenotypes_89ea6547_js_3668118514_5529405417970225995(self):
        self.client.get(url='/js/analyze-phenotypes.89ea6547.js', name='/js/analyze-phenotypes.89ea6547.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(14)
    def GET_https_monarchinitiative_org_1607665813__js_data_sources_787062cf_js_2328037703_351161981702411587(self):
        self.client.get(url='/js/data-sources.787062cf.js', name='/js/data-sources.787062cf.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(15)
    def GET_https_monarchinitiative_org_1607665813__js_licensing_0b7d134c_js_1886062681_7532645875373098679(self):
        self.client.get(url='/js/licensing.0b7d134c.js', name='/js/licensing.0b7d134c.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(16)
    def GET_https_monarchinitiative_org_1607665813__js_mon_analytics_45a0a929_js_2546993587_7347915875825242614(self):
        self.client.get(url='/js/mon-analytics.45a0a929.js', name='/js/mon-analytics.45a0a929.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(17)
    def GET_https_monarchinitiative_org_1607665813__js_routeerror_1e65af9c_js_2141391154_6066091331354000828(self):
        self.client.get(url='/js/routeerror.1e65af9c.js', name='/js/routeerror.1e65af9c.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(18)
    def GET_https_monarchinitiative_org_1607665813__js_search_899cc755_js_1393952508_5404597713048313955(self):
        self.client.get(url='/js/search.899cc755.js', name='/js/search.899cc755.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(19)
    def GET_https_monarchinitiative_org_1607665813__js_text_annotate_64e5a899_js_2582448592_2401646231535263495(self):
        self.client.get(url='/js/text-annotate.64e5a899.js', name='/js/text-annotate.64e5a899.js', timeout=30, allow_redirects=False, headers={'accept': 'application/signed-exchange;v=b3;q=0.9,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'purpose': 'prefetch', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(20)
    def GET_https_monarchinitiative_org_1607665813__img_network_9e85bae7_jpg_1920010413_3925051239646112569(self):
        self.client.get(url='/img/network.9e85bae7.jpg', name='/img/network.9e85bae7.jpg', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/css/app.fe6b0f90.css', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(21)
    def GET_https_fonts_gstatic_com_1028916917__s_poppins_v15_pxiEyp8kv8JHgFVrJJfecnFHGPc_woff2_2641891510_169467042757988581(self):
        self.client.get(url='https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJfecnFHGPc.woff2', name='https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJfecnFHGPc.woff2', timeout=30, allow_redirects=False, headers={'origin': '', 'referer': 'https://fonts.googleapis.com/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(22)
    def GET_https_monarchinitiative_org_1607665813__fonts_fontawesome_webfont_af7ae505_woff2_1199509233_8678393579908464366(self):
        self.client.get(url='/fonts/fontawesome-webfont.af7ae505.woff2', name='/fonts/fontawesome-webfont.af7ae505.woff2', timeout=30, allow_redirects=False, headers={'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'origin': '', 'referer': '/css/chunk-vendors.b5fbaf8f.css', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'font', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(23)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_logo_white_0830f4f0_svg_3964865623_474002267910979118(self):
        self.client.get(url='/img/monarch-logo-white.0830f4f0.svg', name='/img/monarch-logo-white.0830f4f0.svg', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(24)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_logo_white_stacked_bd2e2757_png_1779109775_5564283518093407213(self):
        self.client.get(url='/img/monarch-logo-white-stacked.bd2e2757.png', name='/img/monarch-logo-white-stacked.bd2e2757.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(25)
    def GET_https_monarchinitiative_org_1607665813__img_osu_7096fff0_png_1247676108_2621221284811527551(self):
        self.client.get(url='/img/osu.7096fff0.png', name='/img/osu.7096fff0.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(26)
    def GET_https_monarchinitiative_org_1607665813__img_jackson_7b1eed8a_png_1900284087_3747896837861477836(self):
        self.client.get(url='/img/jackson.7b1eed8a.png', name='/img/jackson.7b1eed8a.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(27)
    def GET_https_monarchinitiative_org_1607665813__img_lbnl_29e333c2_jpeg_1468008260_7270775280682298440(self):
        self.client.get(url='/img/lbnl.29e333c2.jpeg', name='/img/lbnl.29e333c2.jpeg', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(28)
    def GET_https_monarchinitiative_org_1607665813__img_health_ai_f69127f8_png_2107181239_145675822379892444(self):
        self.client.get(url='/img/health-ai.f69127f8.png', name='/img/health-ai.f69127f8.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(29)
    def GET_https_monarchinitiative_org_1607665813__img_qmul_6d87eef5_png_1429473130_6127533359645450159(self):
        self.client.get(url='/img/qmul.6d87eef5.png', name='/img/qmul.6d87eef5.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(30)
    def GET_https_monarchinitiative_org_1607665813__img_ebi_2c6a5935_png_1200948847_3473101787958502513(self):
        self.client.get(url='/img/ebi.2c6a5935.png', name='/img/ebi.2c6a5935.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(31)
    def GET_https_monarchinitiative_org_1607665813__img_renci_9996e65d_png_1504184163_5459356612548645197(self):
        self.client.get(url='/img/renci.9996e65d.png', name='/img/renci.9996e65d.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(32)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_logo_white_418cd8cf_png_4011986102_2013682548767932590(self):
        self.client.get(url='/img/monarch-logo-white.418cd8cf.png', name='/img/monarch-logo-white.418cd8cf.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})

    @seq_task(34)
    def GET_https_monarchinitiative_org_1607665813__mondo_ids_txt_667682170_1686226878077568128(self):
        self.client.get(url='/mondo_ids.txt', name='/mondo_ids.txt', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(35)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0006769_phenotypes_2329808973_1866276558018841503(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0006769/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0006769/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(36)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0005083_phenotypes_2319388737_7545140560285891292(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(37)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0008903_phenotypes_2323779653_8920394074056951976(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0008903/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0008903/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(39)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_MONDO_0006769_2353203394_2991220079117399205(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0006769', name='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0006769', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(40)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_MONDO_0005083_2351433910_2249557150729633155(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0005083', name='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0005083', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(41)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_MONDO_0008903_2352941242_4687917751696146671(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0008903', name='https://api.monarch-test.ddns.net/api/bioentity/MONDO:0008903', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(44)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_354683473811004063(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'cache-control': 'no-cache', 'pragma': 'no-cache', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})

    @seq_task(46)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_ico_1846937856_8316148883513141837(self):
        self.client.get(url='/img/favicon/favicon.ico', name='/img/favicon/favicon.ico', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})

    @seq_task(75)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0005083_4014541763_7731241401702347353(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(76)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_2533154525953452595(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(77)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_MONDO_0005083_3650226955_1644981885287575103(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/MONDO:0005083?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', name='https://api.monarch-test.ddns.net/api/graph/edges/from/MONDO:0005083?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(78)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0005083_phenotypes_2319388737_2875312367523767329(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(79)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_PHENOTYPE_8fd1edd1_png_1263013554_1762030109252317260(self):
        self.client.get(url='/img/monarch-ui-icon_PHENOTYPE.8fd1edd1.png', name='/img/monarch-ui-icon_PHENOTYPE.8fd1edd1.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(80)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_GENE_86a0b6ff_png_37293287_7468296637088635932(self):
        self.client.get(url='/img/monarch-ui-icon_GENE.86a0b6ff.png', name='/img/monarch-ui-icon_GENE.86a0b6ff.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(81)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_VARIANT_f43f1046_png_702942584_7525953690771019524(self):
        self.client.get(url='/img/monarch-ui-icon_VARIANT.f43f1046.png', name='/img/monarch-ui-icon_VARIANT.f43f1046.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(82)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_MODEL_a0fd8e11_png_287051056_8259685471798408624(self):
        self.client.get(url='/img/monarch-ui-icon_MODEL.a0fd8e11.png', name='/img/monarch-ui-icon_MODEL.a0fd8e11.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(83)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_PATHWAYS_123cb200_png_931335619_5461889393364893765(self):
        self.client.get(url='/img/monarch-ui-icon_PATHWAYS.123cb200.png', name='/img/monarch-ui-icon_PATHWAYS.123cb200.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(84)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_PUBLICATION_160b5af0_png_1657016004_3355262990789928810(self):
        self.client.get(url='/img/monarch-ui-icon_PUBLICATION.160b5af0.png', name='/img/monarch-ui-icon_PUBLICATION.160b5af0.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(85)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_GENOTYPE_cbe4bbfd_png_1064373948_7518242421862024682(self):
        self.client.get(url='/img/monarch-ui-icon_GENOTYPE.cbe4bbfd.png', name='/img/monarch-ui-icon_GENOTYPE.cbe4bbfd.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(86)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0005083_phenotypes_2319388737_8030045614942863610(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?fetch_objects=true&start=0&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0005083/phenotypes?fetch_objects=true&start=0&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(87)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_7416649340433459375(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/disease/MONDO:0005083', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(88)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_phenotype_HP_0003765_3899722721_3253718327758631598(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(89)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_4939777400787232740(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/phenotype/HP:0003765', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(90)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_HP_0003765_3069905451_457319029341741768(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/HP:0003765?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', name='https://api.monarch-test.ddns.net/api/graph/edges/from/HP:0003765?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(91)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_DISEASE_bafbacff_png_821497470_9102574525056173034(self):
        self.client.get(url='/img/monarch-ui-icon_DISEASE.bafbacff.png', name='/img/monarch-ui-icon_DISEASE.bafbacff.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/phenotype/HP:0003765', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(92)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_phenotype_HP_0003765_variants_1682509688_2712304432729156430(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765/variants?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=subject_taxon', name='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765/variants?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=subject_taxon', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(93)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_2915323772695194024(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/phenotype/HP:0003765', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(94)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_phenotype_HP_0003765_genes_922619426_2185149579568507928(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765/genes?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=object_taxon', name='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0003765/genes?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=object_taxon', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(95)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_9080691024377781967(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/phenotype/HP:0003765', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(96)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_2615347604_2633219262997186569(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(97)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_6492090771060673103(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(98)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_HGNC_6601_2915437083_2096490423437617876(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(102)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_PHENOTYPE_8fd1edd1_png_1263013554_1131586343551803646(self):
        self.client.get(url='/img/monarch-ui-icon_PHENOTYPE.8fd1edd1.png', name='/img/monarch-ui-icon_PHENOTYPE.8fd1edd1.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"3e0fb4f81234c1d5abb3a70e39184279-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(103)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_MODEL_a0fd8e11_png_287051056_7363127976754969666(self):
        self.client.get(url='/img/monarch-ui-icon_MODEL.a0fd8e11.png', name='/img/monarch-ui-icon_MODEL.a0fd8e11.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"e0f33bd723782545d8c36c9a79371859-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(104)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_ANATOMY_dfa2358b_png_755371485_2088962996408103061(self):
        self.client.get(url='/img/monarch-ui-icon_ANATOMY.dfa2358b.png', name='/img/monarch-ui-icon_ANATOMY.dfa2358b.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(105)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_FUNCTION_14e9b5fe_png_970460720_4391321479951736854(self):
        self.client.get(url='/img/monarch-ui-icon_FUNCTION.14e9b5fe.png', name='/img/monarch-ui-icon_FUNCTION.14e9b5fe.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(106)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_HOMOLOG_ce2c8924_png_740298158_2048281920676310707(self):
        self.client.get(url='/img/monarch-ui-icon_HOMOLOG.ce2c8924.png', name='/img/monarch-ui-icon_HOMOLOG.ce2c8924.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(107)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_INTERACTIONS_7aad1b54_png_1973817169_4531374714434620228(self):
        self.client.get(url='/img/monarch-ui-icon_INTERACTIONS.7aad1b54.png', name='/img/monarch-ui-icon_INTERACTIONS.7aad1b54.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(108)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_ORTHOLOG_PHENOTYPE_b053c4ec_png_3660845383_4202789228402235182(self):
        self.client.get(url='/img/monarch-ui-icon_ORTHOLOG_PHENOTYPE.b053c4ec.png', name='/img/monarch-ui-icon_ORTHOLOG_PHENOTYPE.b053c4ec.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(109)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_publications_998706896_9115270073541702328(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(110)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_7102867670386848043(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})

    @seq_task(113)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_publication_ZFIN_ZDB_PUB_030905_1_2812612489_8711062236809022538(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/publication/ZFIN:ZDB-PUB-030905-1?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/publication/ZFIN:ZDB-PUB-030905-1?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(114)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_6735852901557837697(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/publication/ZFIN:ZDB-PUB-030905-1', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(115)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_ZFIN_ZDB_PUB_030905_1_1062997269_7151015332700879671(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/ZFIN:ZDB-PUB-030905-1?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/ZFIN:ZDB-PUB-030905-1?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(118)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_2615347604_6084167529110401458(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(119)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_8914318811520141338(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(120)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_HGNC_6601_2915437083_7728111859241747682(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(125)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_publications_998706896_615608992376480584(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(128)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_publication_PMID_11349135_760548711_104459441776205358(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/publication/PMID:11349135?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/publication/PMID:11349135?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(129)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_3325829604713780433(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/publication/PMID:11349135', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(130)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_PMID_11349135_3634170611_9059837490172403005(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/PMID:11349135?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/PMID:11349135?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(133)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_2615347604_392832363963274231(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(134)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_5524200898828743255(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(135)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_HGNC_6601_2915437083_4283297741596213175(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/HGNC:6601?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(139)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_publications_998706896_3350294511936007667(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=0&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(142)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_publications_998706896_2938603738780871067(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=15&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/publications?fetch_objects=true&start=15&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(145)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_HGNC_6601_homologs_51186987_9155588127303708841(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/homologs?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=object_taxon', name='https://api.monarch-test.ddns.net/api/bioentity/gene/HGNC:6601/homologs?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=object_taxon', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(146)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_4948077960639945464(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/HGNC:6601', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(147)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_FlyBase_FBgn0030506_425790728_4368944604508126181(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/FlyBase:FBgn0030506?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/gene/FlyBase:FBgn0030506?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(148)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_5422965749893182879(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/FlyBase:FBgn0030506', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(149)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_FlyBase_FBgn0030506_814353807_7349014314184336898(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/FlyBase:FBgn0030506?relationship_type=equivalentClass', name='https://api.monarch-test.ddns.net/api/graph/edges/from/FlyBase:FBgn0030506?relationship_type=equivalentClass', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})

    @seq_task(153)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_ORTHOLOG_DISEASE_76865641_png_2965508059_3823460610820343963(self):
        self.client.get(url='/img/monarch-ui-icon_ORTHOLOG_DISEASE.76865641.png', name='/img/monarch-ui-icon_ORTHOLOG_DISEASE.76865641.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'referer': '/gene/FlyBase:FBgn0030506', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(154)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_gene_FlyBase_FBgn0030506_ortholog_diseases_1177687077_3364858757561852248(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/gene/FlyBase:FBgn0030506/ortholog/diseases?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=subject_taxon', name='https://api.monarch-test.ddns.net/api/bioentity/gene/FlyBase:FBgn0030506/ortholog/diseases?fetch_objects=true&start=0&rows=15&unselect_evidence=true&facet=true&facet_fields=subject_taxon', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(155)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_872121615369280110(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/gene/FlyBase:FBgn0030506', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(157)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0011338_4014083011_6958238076944062511(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(158)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_2200525881247714706(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(159)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_MONDO_0011338_3649768203_1288492205282677198(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/MONDO:0011338?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', name='https://api.monarch-test.ddns.net/api/graph/edges/from/MONDO:0011338?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(160)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0011338_phenotypes_2318929985_5682972161130916104(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338/phenotypes?rows=0&facet=true&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false&direct=false&direct_taxon=false', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(161)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_GENE_86a0b6ff_png_37293287_2594848939693454666(self):
        self.client.get(url='/img/monarch-ui-icon_GENE.86a0b6ff.png', name='/img/monarch-ui-icon_GENE.86a0b6ff.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"6b14b08504ca9841bcae3f476e4f5bc5-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(162)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_MODEL_a0fd8e11_png_287051056_5975981733796660798(self):
        self.client.get(url='/img/monarch-ui-icon_MODEL.a0fd8e11.png', name='/img/monarch-ui-icon_MODEL.a0fd8e11.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"e0f33bd723782545d8c36c9a79371859-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(163)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_PATHWAYS_123cb200_png_931335619_6706154466016078011(self):
        self.client.get(url='/img/monarch-ui-icon_PATHWAYS.123cb200.png', name='/img/monarch-ui-icon_PATHWAYS.123cb200.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"86cb45c01ddb3c4decf5ca09ccf5a742-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(164)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_GENOTYPE_cbe4bbfd_png_1064373948_5503372955506962244(self):
        self.client.get(url='/img/monarch-ui-icon_GENOTYPE.cbe4bbfd.png', name='/img/monarch-ui-icon_GENOTYPE.cbe4bbfd.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"d6c77f939aa36bd30b30dc8e9882e68f-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(165)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_disease_MONDO_0011338_phenotypes_2318929985_420265279300016615(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338/phenotypes?fetch_objects=true&start=0&rows=15&unselect_evidence=true', name='https://api.monarch-test.ddns.net/api/bioentity/disease/MONDO:0011338/phenotypes?fetch_objects=true&start=0&rows=15&unselect_evidence=true', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(166)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_6106479289002451574(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/disease/MONDO:0011338', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(167)
    def GET_https_api_monarchinitiative_org_2167605757__api_bioentity_phenotype_HP_0002718_3899001822_7520790442589819918(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0002718?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', name='https://api.monarch-test.ddns.net/api/bioentity/phenotype/HP:0002718?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(168)
    def GET_https_monarchinitiative_org_1607665813__img_favicon_favicon_png_1849231626_2107912444327418505(self):
        self.client.get(url='/img/favicon/favicon.png', name='/img/favicon/favicon.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"9259dd9a47acc938ff925fb689d9d77c-ssl"', 'referer': '/phenotype/HP:0002718', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})
    
    @seq_task(169)
    def GET_https_api_monarchinitiative_org_2167605757__api_graph_edges_from_HP_0002718_3069184552_3140873583218176666(self):
        self.client.get(url='https://api.monarch-test.ddns.net/api/graph/edges/from/HP:0002718?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', name='https://api.monarch-test.ddns.net/api/graph/edges/from/HP:0002718?relationship_type=equivalentClass&relationship_type=subClassOf&relationship_type=BFO%3A0000050', timeout=30, allow_redirects=False, headers={'accept': 'application/json, text/plain, */*', 'referer': '/', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0'})
    
    @seq_task(170)
    def GET_https_monarchinitiative_org_1607665813__img_monarch_ui_icon_DISEASE_bafbacff_png_821497470_1978277371271686414(self):
        self.client.get(url='/img/monarch-ui-icon_DISEASE.bafbacff.png', name='/img/monarch-ui-icon_DISEASE.bafbacff.png', timeout=30, allow_redirects=False, headers={'accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US,en;q=0.9', 'if-none-match': '"80dd30104a6ef37bbdfd2e6f80880ae9-ssl"', 'referer': '/phenotype/HP:0002718', 'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"', 'sec-ch-ua-mobile': '?0', 'sec-fetch-dest': 'image', 'sec-fetch-mode': 'no-cors', 'sec-fetch-site': 'same-origin', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'})

class LocustFormonarch_random_182055_har_2011367572(HttpLocust):
    if LOCUST_MAJOR_VERSION >= 1:
        tasks = [monarch_random_182055_har_2011367572]
    else:
        task_set = monarch_random_182055_har_2011367572

    weight = 1
    min_wait = 0
    max_wait = 10
